name: "TMDb Trailers"
guid: "69104C31-D23F-4040-B99C-8913C09751D6"
version: .0.0
targetAbi: "10.11.5.0"
framework: "net9.0"
owner: "solumos"
overview: "Watch trailers from TMDb"
imageUrl: "https://raw.githubusercontent.com/solumos/jellyfin-plugin-tmdb-trailers/master/Jellyfin.Plugin.Tmdb.Trailers/Images/jellyfin-plugin-tmdb.png"
description: >
  Watch trailers from TMDb

category: "Channels"
artifacts:
  - "Jellyfin.Plugin.Tmdb.Trailers.dll"
  - "TMDbLib.dll"
  - "AngleSharp.dll"
  - "CliWrap.dll"
  - "YoutubeExplode.dll"
  - "YoutubeExplode.Converter.dll"
changelog: |-
  - feat: add initialization logging for IntroManager (#1) @solumos
